package com.networktools.opencode.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF005AC1)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD8E2FF)
val LightOnPrimaryContainer = Color(0xFF001945)

val LightSecondary = Color(0xFF575E71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDBE2F9)
val LightOnSecondaryContainer = Color(0xFF141B2C)

val LightTertiary = Color(0xFF715573)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFBD7FB)
val LightOnTertiaryContainer = Color(0xFF29132C)

val LightBackground = Color(0xFFF8FAFF)
val LightOnBackground = Color(0xFF1A1B21)
val LightSurface = Color(0xFFFDFBFF)
val LightOnSurface = Color(0xFF1A1B21)
val LightSurfaceVariant = Color(0xFFE2E2EC)
val LightOnSurfaceVariant = Color(0xFF44474F)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightSurfaceContainer = Color(0xFFECEDF5)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF2F3FA)
val LightSurfaceContainerHigh = Color(0xFFE6E7F0)
val LightSurfaceContainerHighest = Color(0xFFE0E2EB)
val LightOutline = Color(0xFF74777F)

val DarkPrimary = Color(0xFFADC6FF)
val DarkOnPrimary = Color(0xFF002E69)
val DarkPrimaryContainer = Color(0xFF004494)
val DarkOnPrimaryContainer = Color(0xFFD8E2FF)

val DarkSecondary = Color(0xFFBFC6DC)
val DarkOnSecondary = Color(0xFF293041)
val DarkSecondaryContainer = Color(0xFF3F4759)
val DarkOnSecondaryContainer = Color(0xFFDBE2F9)

val DarkTertiary = Color(0xFFE2BBE3)
val DarkOnTertiary = Color(0xFF402743)
val DarkTertiaryContainer = Color(0xFF583D5B)
val DarkOnTertiaryContainer = Color(0xFFFBD7FB)

val DarkBackground = Color(0xFF000000)
val DarkOnBackground = Color(0xFFE3E1E9)
val DarkSurface = Color(0xFF000000)
val DarkOnSurface = Color(0xFFE3E1E9)
val DarkSurfaceVariant = Color(0xFF44474F)
val DarkOnSurfaceVariant = Color(0xFFC4C6D0)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkSurfaceContainer = Color(0xFF121218)
val DarkSurfaceContainerLowest = Color(0xFF000000)
val DarkSurfaceContainerLow = Color(0xFF0E0E13)
val DarkSurfaceContainerHigh = Color(0xFF1C1C22)
val DarkSurfaceContainerHighest = Color(0xFF202027)
val DarkOutline = Color(0xFF8E9099)
